ballerina-platform/module-ballerinax-azure.functions

azurefunctions-extension-balo/build.gradle, azurefunctions-extension-balo/src/azure.functions/code.bal, gradle.properties
=> Fixes related to 1.2.x releases

azurefunctions-extension-balo/src/azure.functions/code.bal, azurefunctions-extension-examples/build.gradle, azurefunctions-extension-examples/examples/azurefunctions-deployment/azure_functions_deployment.bal, azurefunctions-extension-examples/examples/azurefunctions-deployment/azure_functions_deployment.description, azurefunctions-extension-examples/examples/azurefunctions-deployment/azure_functions_deployment.out, azurefunctions-extension-examples/examples/index.js, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/cosmosdb/CosmosDBReturnHandler.java
=> Add Azure Functions BBE and CosmosDB Partition Key Fix

azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/AzureFunctionsPlugin.java
=> Fix non-Azure Functions applications not exiting issue

gradle.properties
=> Sync ballerina-1.2.x with release-1.2.5 branch

gradle.properties
=> Bump version to 1.2.6

build.gradle
=> Add 1.2.6 staging repo for ballerina-lang

README.md, azurefunctions-extension-balo/src/azure.functions/code.bal, azurefunctions-extension-examples/examples/azure-functions-deployment/azure_functions_deployment.bal, azurefunctions-extension-test/src/test/resources/deployment/functions.bal, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/cosmosdb/CosmosDBReturnHandler.java
=> Fix for paritition key issue

azurefunctions-extension-balo/build.gradle, azurefunctions-extension-balo/src/azure.functions/Module.md, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/AzureFunctionsPlugin.java, gradle.properties
=> Update build to be included in swan lake release

README.md, azurefunctions-extension-balo/src/azure.functions/Module.md
Update the Java version to 8.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Update the Java Version to 8

azurefunctions-extension-examples/examples/azure-functions-deployment/azure_functions_deployment.description
Fix the "Deployment Guide" Link in the Azure BBE in Swan Lake. …
=> Fix the "Deployment Guide" Link in the Azure BBE in Swan Lake

azurefunctions-extension-examples/examples/azure-functions-deployment/azure_functions_deployment.description
Update the "Deployment Guide" Link in the Azure BBE for 1.2.x. …
=> Update the "Deployment Guide" Link in the Azure BBE for 1.2.x

azurefunctions-extension-balo/src/azure.functions/Module.md
Add the BBE link to the Module in Swan Lake API Docs. …
=> Add the BBE Link to the Module in Swan Lake API Docs

azurefunctions-extension-balo/src/azure.functions/Module.md
Add the BBE Link in 1.2.x API Docs. …
=> Add the BBE Link in 1.2.x API Docs

azurefunctions-extension-balo/src/azure.functions/Module.md
Add the Deployment Guide link in API Docs 1.2.x. …
=> Add the Deployment Guide Link in API Docs 1.2.x

azurefunctions-extension-balo/src/azure.functions/Module.md
Add the Deployment Guide link in API Docs Swan Lake. …
=> Add the Deployment Guide Link in API Docs Swan Lake

README.md, azurefunctions-extension-balo/src/azure.functions/Module.md, azurefunctions-extension-balo/src/azure.functions/annotation.bal, azurefunctions-extension-balo/src/azure.functions/code.bal, azurefunctions-extension-examples/examples/azure-functions-deployment/azure_functions_deployment.bal, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/Constants.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/FunctionsArtifact.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/Utils.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/blob/BlobInputParameterHandler.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/blob/BlobOutputParameterHandler.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/blob/BlobTriggerParameterHandler.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/cosmosdb/CosmosDBInputParameterHandler.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/cosmosdb/CosmosDBReturnHandler.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/cosmosdb/CosmosDBTriggerHandler.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/http/HTTPReturnHandler.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/http/HTTPTriggerParameterHandler.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/metadata/MetadataBindingParameterHandler.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/queue/QueueOutputParameterHandler.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/queue/QueueTriggerHandler.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/timer/TimerTriggerHandler.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/twilio/TwilioSmsOutputParameterHandler.java
=> Functionality Fixes and Improvements in Debugging

README.md, azurefunctions-extension-balo/src/azure.functions/Module.md, azurefunctions-extension-examples/examples/azure-functions-deployment/azure_functions_deployment.bal
=> Fix example code formatting

build.gradle, gradle.properties
=> Sync ballerina-1.2.x branch with 1.2.7 release

azurefunctions-extension-examples/examples/azure-functions-deployment/azure_functions_deployment.description
Fix the broken link in the Azure Functions BBE. …
=> Fix the Broken Link in the Azure Functions BBE

azurefunctions-extension-balo/src/azure.functions/Module.md
Update relative paths of 1.2 API docs. …
=> Update Relative Paths of 1.2 API Docs

azurefunctions-extension-balo/src/azure.functions/Module.md
Update relative paths of Swan Lake API docs. …
=> Update Relative Paths of Swan Lake API Docs

gradle.properties
=> Sync 1.2.x branch with 1.2.8 release

build.gradle, gradle.properties
=> Sync ballerina-1.2.x branch with 1.2.8 release

gradle.properties
=> Sync master with release-2.0.0-Preview3

azurefunctions-extension-balo/src/azure.functions/code.bal, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/Utils.java
- Update object definition
- Update SymbolOrigin
=> Update to new Ballerina syntax

.github/workflows/build.yml, azurefunctions-extension-balo/src/azure.functions/code.bal
- Apply isolated function changes
=> Apply isolated function changes

build.gradle, gradle.properties
$subject
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
=> Use separate property for ballerina-lang

azurefunctions-extension-balo/src/azure.functions/Module.md
=> Remove Object Links

azurefunctions-extension-balo/Ballerina.toml
- Change module version to 1.0.0
- Resolves https://github.com/ballerina-platform/ballerina-lang/issues/25507
=> Fix module version

gradle.properties
=> Release 1.2.9

gradle.properties
=> Release 1.2.10

azurefunctions-extension-test/src/test/java/org/ballerinax/azurefunctions/test/utils/TestUtils.java, azurefunctions-extension-test/src/test/resources/deployment/Ballerina.toml, azurefunctions-extension-test/src/test/resources/testng.xml, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/AzureFunctionsPlugin.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/Constants.java
- Enable azure functions test cases
- Fix azure functions test cases
=> Enable test cases

azurefunctions-extension-balo/build.gradle
- Fix multiple slf4j binding issue
=> Fix slf4j binding

azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/AzureFunctionsPlugin.java
=> Fix output zip path

.github/workflows/daily-build.yml, .github/workflows/publish-release.yml, azurefunctions-extension-balo/build.gradle, azurefunctions-extension-examples/build.gradle
- Add Github release workflows
=> Add Github release workflows

build.gradle
=> Add mavenCentral repository

gradle/javaProject.gradle
=> Enable jar publishing

.github/workflows/build-master.yml
=> Add trigger for master branch build

azurefunctions-extension-balo/code.bal, azurefunctions-extension/build.gradle, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/AzureFunctionsPlugin.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/GlobalContext.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/Utils.java
- Add dummy listener
- Workaround for https://github.com/ballerina-platform/ballerina-lang/issues/27529
=> Add dummy listener

azurefunctions-extension-balo/Package.md
=> Fix documentation syntax

azurefunctions-extension-balo/Package.md
- Fix module overview document
=> Fix module overview

gradle.properties
=> Sync after Release 1.2.11

build.gradle, gradle.properties
=> Sync after Release 1.2.12

gradle.properties
=> Sync after release 1.2.13

README.md, gradle.properties
- Update Ballerina version to 2.0.0-alpha-SNAPSHOT
=> Update Ballerina version

azurefunctions-extension-examples/examples/azure-functions-deployment/azure_functions_deployment.bal
Removes system module and introduced uuid module to generate ids in BBEs. …
=> Fix uuids in BBE

azurefunctions-extension-examples/examples/azure-functions-deployment/azure_functions_deployment.description
Fix the broken link in Azure Functions BBE. …
=> Fix the Broken Link in Azure Functions BBE

azurefunctions-extension-bala/code.bal, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/blob/BlobOutputParameterHandler.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/cosmosdb/CosmosDBInputParameterHandler.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/handlers/queue/QueueTriggerHandler.java
=> Fix JSON related encoding issues and clean up the code

azurefunctions-extension-bala/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
=> Add extracted bala in the zip artifact

azurefunctions-extension-bala/Package.md
> Fix links in Package.md
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Fix broken links

.github/workflows/publish-release.yml, .github/workflows/pull-request.yml
=> Ignore branches for push builds

build.gradle, gradle.properties
=> Standardise dependency names

README.md, azurefunctions-extension-examples/examples/azure-functions-deployment/azure_functions_deployment.bal, azurefunctions-extension-test/src/test/resources/deployment/functions.bal, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/Utils.java
Adds support for empty key value annotations for improved readability and usability.
> Link to the PR for changes to the training …
=> Add support for empty key value annotations

.github/workflows/build-master.yml
=> Introduce timestamped snapshot release

gradle.properties
=> Sync after Release 1.2.14

gradle.properties
=> Bump ballerina version to 1.2.15

.github/workflows/build-master.yml
=> Standardise build name

settings.gradle
=> Remove BBE entry from gradle

gradle.properties
=> Bump version to 1.2.16

gradle.properties
=> Sync 1.2.x Branch After Release 1.2.16

gradle.properties
=> Sync 1.2.x Branch After 1.2.17 Release

build.gradle, gradle.properties
=> Ballerina 1.2.x

azurefunctions-extension-test/src/test/resources/deployment/functions.bal, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/Utils.java
=> Improve codecov and remove unused code

gradle.properties
=> Sync 1.2.x Branch After 1.2.18 Release

gradle.properties
=> Merge ballerina-1.2.x into release-stage-1.2.x

gradle.properties
=> Sync 1.2.x Branch After 1.2.19 Release

gradle.properties
=> Sync 1.2.x after release 1.2.20

gradle.properties
=> Update version to 1.2.21

gradle.properties
=> Sync 1.2.x after release 1.2.21

azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/FunctionsArtifact.java
$Subject as Azure runtime recently restricted 1.8.x.  …
=> Bump azure functions extension bundle

gradle.properties
=> Update ballerina version to 1.2.22

gradle.properties
=> Sync with Release 1.2.22

gradle.properties
=> Update version to 1.2.23

gradle.properties
=> Sync with release 1.2.23

azurefunctions-extension-test/src/test/java/org/ballerinax/azurefunctions/test/DeploymentTest.java, azurefunctions-extension-test/src/test/java/org/ballerinax/azurefunctions/test/utils/TestUtils.java, azurefunctions-extension-test/src/test/resources/single_file/functions.bal, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/AzureFunctionsPlugin.java
$Subject. as the new compiler ext does not single file project codegen. …
=> Disallow single file projects for azure functions

gradle.properties
=> Sync 1.2.x branch with stage-1.2.24 post release

gradle.properties
=> Update commons io version

gradle.properties
=> Merge release 1.2.25 into stage 1.2.25

gradle.properties
=> Merge stage 1.2.25 into 1.2.x

azurefunctions-extension/build.gradle, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/AzureFunctionsPlugin.java, azurefunctions-extension/src/main/java/org/ballerinax/azurefunctions/ParameterHandler.java, gradle.properties
$Subject as ballerina-core package is removed from the lang. …
=> Remove usage of ballerina-core with latest lang

ballerina-tests/build.gradle, ballerina/build.gradle
=> Fix gradle publish

gradle.properties
=> Sync ballerina 1.2.x with release 1.2.27

ballerina-tests/Ballerina.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, gradle.properties, gradle/wrapper/gradle-wrapper.properties
Earlier we bumped a major version, however, we decided as another rewrite is coming up, to make this a minor version bump.  therefore 3.0.0 -> 2.1.0
We observed some logs from Gradle 7.2 on invalid gradle steps. We need to migrate to 7.2 properly(#444) . Downgraded gradle to earlier version (6.2) till then. 
> Brief description of the new feature or bug fix as it will …
=> Change the version bump to minor bump and change Gradle Version

gradle.properties
=> Sync ballerina-1.2.x with release-1.2.28

gradle.properties
=> Bump lang version to update 1

gradle.properties
=> Sync with release 1.2.29

gradle.properties
=> Sync with Release 1.2.30

ballerina-tests/main.bal, ballerina-tests/tests/resources/httpAccessorTest.json, ballerina-tests/tests/resources/nonHttpResTest.json, ballerina-tests/tests/resources/nonHttpResTest1.json, ballerina-tests/tests/resources/nonReturnTest1.json, ballerina-tests/tests/test.bal, native/src/main/java/io/ballerina/stdlib/azure/functions/Constants.java, native/src/main/java/io/ballerina/stdlib/azure/functions/FunctionCallback.java, native/src/main/java/io/ballerina/stdlib/azure/functions/NativeHttpToAzureAdaptor.java, native/src/main/java/io/ballerina/stdlib/azure/functions/NativeRemoteAdapter.java
=> Implement HTTP Return implicit status codes and content types

gradle.properties
=> Sync with release 1.2.31

ballerina-tests/tests/resources/httpHeaderTest.json, native/src/main/java/io/ballerina/stdlib/azure/functions/HttpResource.java
=> Fix bug for header annotation implementation

gradle.properties
=> Sync with release 1.2.32

compiler-plugin/spotbugs-exclude.xml, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/AzureCodeGeneratedTask.java, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/Constants.java, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/FunctionsArtifact.java, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/tooling/Extensions.java, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/tooling/LocalSettings.java, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/tooling/Settings.java, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/tooling/Tasks.java
$Subject.
Resolves https://github.com/ballerina-platform/module-ballerinax-azure.functions/issues/514
Resolves https://github.com/ballerina-platform/module-ballerinax-azure.functions/issues/515
Deploying is not supported for non native build due to https://github.com/microsoft/vscode-azurefunctions/issues/3361 . 
> Brief description of the new feature or bug fix as it …
=> Add azure functions tooling artifact generation

gradle.properties
=> Sync with Release 1.2.33

ballerina-tests/build.gradle
=> Add code coverage for ballerina tests

ballerina/Package.md
$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3463
> Link to the PR for changes to …
=> Replace slack with discord

ballerina-tests/Ballerina.toml, ballerina/Dependencies.toml, ballerina/annotation.bal, ballerina/dispatcher_service.bal, ballerina/http_service.bal, build-config/resources/BallerinaTest.toml, compiler-plugin-tests/src/test/resources/handlers/Ballerina.toml, compiler-plugin-tests/src/test/resources/handlers/main.bal, compiler-plugin-tests/src/test/resources/validations/http-header-annotation/Ballerina.toml, compiler-plugin-tests/src/test/resources/validations/http-service-config/Ballerina.toml, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/AzureFunctionServiceVisitor.java, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/Util.java, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/service/ServiceHandler.java
$Subject
Resolves https://github.com/ballerina-platform/module-ballerinax-azure.functions/issues/555
Resolves https://github.com/ballerina-platform/module-ballerinax-azure.functions/issues/551
Removes unwanted annotation attachments
Fixes compiler extension related bugs for separate listeners
> Brief description of the new feature or bug fix as it will appear in the …
=> Minor bug fixes and improvments

README.md, ballerina-tests/Ballerina.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/Module.md, ballerina/Package.md, build-config/resources/BallerinaTest.toml, compiler-plugin-tests/src/test/resources/handlers/Ballerina.toml, compiler-plugin-tests/src/test/resources/validations/http-header-annotation/Ballerina.toml, compiler-plugin-tests/src/test/resources/validations/http-service-config/Ballerina.toml, gradle.properties
$Subject. To do the 3.0.0 Release
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …
=> Add documentation and Change version to stable from alpha

gradle.properties
=> Update version to 1.2.34

gradle.properties
=> Sync 1.2.x with release 1.2.34

ballerina-tests/tests/http_validation.bal, ballerina-tests/tests/main.bal, ballerina-tests/tests/resources/http/input/cosmos/empty.json, ballerina-tests/tests/resources/http/input/cosmos/invalid.json, ballerina-tests/tests/resources/http/input/cosmos/valid.json, ballerina-tests/tests/resources/http/path/invalid-payload.json, ballerina-tests/tests/resources/http/path/valid.json, ballerina-tests/tests/resources/http/payload/invalid-payload.json, ballerina-tests/tests/resources/http/payload/optional-invalid.json, ballerina-tests/tests/resources/http/payload/optional-negative.json, ballerina-tests/tests/resources/http/payload/optional-positive.json, ballerina-tests/tests/resources/http/query/invalid-payload.json, ballerina-tests/tests/resources/http/query/optional-invalid.json, ballerina-tests/tests/resources/http/query/optional-negative.json, ballerina-tests/tests/resources/http/query/optional-positive.json, ballerina-tests/tests/test.bal, ballerina/Dependencies.toml, ballerina/http_service.bal, compiler-plugin-tests/src/test/java/org/ballerinax/azurefunctions/test/CustomHostTest.java, compiler-plugin-tests/src/test/java/org/ballerinax/azurefunctions/test/DeploymentTest.java, compiler-plugin-tests/src/test/java/org/ballerinax/azurefunctions/test/NativeTest.java, compiler-plugin-tests/src/test/java/org/ballerinax/azurefunctions/test/utils/TestUtils.java, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/AzureCodeGeneratedTask.java, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/DockerBuildException.java, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/NativeFunctionsArtifact.java, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/service/http/HTTPTriggerBinding.java, native/src/main/java/io/ballerina/stdlib/azure/functions/Constants.java, native/src/main/java/io/ballerina/stdlib/azure/functions/FunctionCallback.java, native/src/main/java/io/ballerina/stdlib/azure/functions/HttpResource.java, native/src/main/java/io/ballerina/stdlib/azure/functions/Utils.java
$Subject
Resolves #600
Resolves #599
Resolves #597 …
=> Fix optionals related bugs and minor refactoring

ballerina-tests/tests/test.bal, native/src/main/java/io/ballerina/stdlib/azure/functions/FunctionCallback.java
$Subject
Resolves #601
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …
=> Fix implicit content type for http status code responses

gradle.properties
=> [ballerina-1.2.x] Prepare for next development iteration

gradle.properties
=> Sync zure.functions `1.2.x` with release `1.2.36`

ballerina-tests/tests/main.bal, ballerina/blob_listener.bal, ballerina/cosmos_listener.bal, ballerina/service_types.bal, compiler-plugin-tests/src/test/resources/handlers/main.bal, compiler-plugin-tests/src/test/resources/validations/http/function-types/main.bal, compiler-plugin-tests/src/test/resources/validations/output/remote-missing-annot/main.bal, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/service/RemoteTriggerBinding.java, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/service/blob/BlobTriggerBinding.java, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/service/cosmosdb/CosmosDBTriggerBinding.java, native/src/main/java/io/ballerina/stdlib/azure/functions/NativeRemoteAdapter.java, spec/spec.md
$Subject. and minor remote functions related fixes …
=> Change remote functions (onUpdated -> OnUpdate)

ballerina-tests/tests/main.bal, ballerina-tests/tests/resources/custom-func-name.json, ballerina-tests/tests/test.bal, ballerina/Dependencies.toml, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/AzureFunctionModifier.java
=> Add custom function name support for HTTP

gradle.properties
=> Update lang version for 1.2.37

gradle.properties
=> Update version to `1.2.38`

gradle.properties
=> Sync `ballerina-1.2.x` with `release-1.2.38`

ballerina-tests/tests/http_validation.bal, native/src/main/java/io/ballerina/stdlib/azure/functions/builder/JsonPayloadBuilder.java, native/src/main/java/io/ballerina/stdlib/azure/functions/converter/JsonToRecordConverter.java
Partially fixes the issue https://github.com/ballerina-platform/ballerina-standard-library/issues/3933
=> Use convert API instead of `CloneWithType`

ballerina-tests/Ballerina.toml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, compiler-plugin-tests/src/test/java/org/ballerinax/azurefunctions/test/FunctionArtifactTest.java, compiler-plugin-tests/src/test/resources/handlers/main.bal, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/service/OutputBindingBuilder.java
=> Fix artifact generation for tuple union types

compiler-plugin/src/main/java/org/ballerinax/azurefunctions/Constants.java, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/FunctionsArtifact.java
$Subject
Resolves https://github.com/ballerina-platform/module-ballerinax-azure.functions/issues/642
> Link to the PR for changes …
=> Add debug flags for artifact generation

gradle.properties
=> Update release version in gradle.properties

.github/workflows/build-master.yml, .github/workflows/daily-build.yml, .github/workflows/publish-release.yml, .github/workflows/pull-request.yml, README.md, ballerina/Ballerina.toml, ballerina/Package.md, build-config/checkstyle/build.gradle, build-config/resources/Ballerina.toml, build.gradle, compiler-plugin-tests/build.gradle, compiler-plugin/spotbugs-exclude.xml, gradle/javaProject.gradle, gradle/wrapper/gradle-wrapper.properties, native-builder/Dockerfile, native/build.gradle, native/spotbugs-exclude.xml, native/src/main/java/io/ballerina/stdlib/azure/functions/builder/FormPayloadBuilder.java, settings.gradle
=> Migrate to Java 17

gradle.properties
=> Sync `1.2.x` after `1.2.40` release

gradle.properties
=> Sync `1.2.x` after `1.2.42` release

gradle.properties
=> Sync `ballerina-1.2.x` after  `1.2.43` release

native-builder/Dockerfile, native-builder/build-native.sh
=> Bump graalvm version and add mostly static flag

gradle.properties
=> Sync release-1.2.44 with 1.2.x

ballerina/Dependencies.toml, native-builder/Dockerfile, native-builder/build-native.sh
$Subject
Resolves https://github.com/ballerina-platform/module-ballerinax-azure.functions/issues/663
> Link to the PR for changes …
=> Change native builder base image and add mostly static

.github/workflows/build-master.yml, .github/workflows/daily-build.yml, .github/workflows/pull-request.yml, compiler-plugin/src/main/java/org/ballerinax/azurefunctions/Constants.java
=> [2201.7.x] Bump builder image

gradle.properties
=> Sync release-1.2.45 with 1.2.x

gradle.properties
=> Sync release-1.2.47 with 1.2.x

gradle.properties
=> [Gradle Release Plugin] - new version commit:  'v1.2.48-SNAPSHOT'.

gradle.properties
=> Update gradle.properties for release 1.2.48

gradle.properties
> Updating the version for `1.2.49` release …
=> Bump version to 1.2.49 for next release

gradle.properties
=> Sync ballerina-1.2.49-stage with ballerina-1.2.x branch

gradle.properties
=> Bump version to 1.2.50

gradle.properties
=> Sync 1.2.x after 1.2.50 release 

gradle.properties
=> Sync `1.2.x` after `1.2.50` release

gradle.properties
=> Sync `1.2.x` after `1.2.51` release

gradle.properties
=> [Gradle Release Plugin] - new version commit:  'v1.2.54'.

gradle.properties
=> Bump azure functions version

gradle.properties
=> Sync 1.2.x after 1.2.57 release
